name: Ship wordpress app to staging
on:
  push:
    branches:
      staging
jobs:
  pull:
    name: Pull new files on server
    runs-on: ubuntu-latest
    steps:
    - name: CD in dir
      uses: appleboy/ssh-action@master
      with:
        host: 178.62.227.94
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: bash /root/nvt-onderhoudendgoed/backend/bin/build.sh
